# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyShortName', models.CharField(max_length=30)),
                ('companySize', models.CharField(max_length=250)),
                ('positionName', models.CharField(max_length=260)),
                ('salary', models.CharField(max_length=230)),
                ('positionAdvantage', models.CharField(max_length=250)),
                ('workYear', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=30)),
                ('createTime', models.DateField()),
            ],
        ),
    ]
